### ISSUE TITLE
repository의 about 오타

### ISSUE THREAD

**Issue by MagicalLas** [CodeSoom/spring-week6-assignment-1#9]
이 repository의 about에 `코드슴`이라는 오타가 있네요! `코드숨`으로 변경하면 좋을 것 같아요.

<img width="303" alt="스크린샷 2021-03-02 오후 10 00 24" src="https://user-images.githubusercontent.com/35015234/109652165-c3831c00-7ba2-11eb-9364-f66ff1437abd.png">

**Comment by hannut91** [comment]
수정했습니다 감사합니다 ㅎㅎ
